spring:
  application:
    name: uwati-profile
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:10000"
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: kotabangun1

server:
  port: ${PROFILE_PORT:10010}

graphql:
  tools:
    schema-location-pattern: "**/graphqls/*.graphqls"
