spring:
  application:
    name: uwati-profile
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:10000"

server:
  port: ${PROFILE_PORT:10010}

graphql:
  servlet:
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/graphqls/*.graphqls"
